'use client'

// Campaign detail — inline-editable shot table generated by the Campaign
// Planner. User can tick/untick, edit hook/caption/setting/duration/aspect
// in place, delete rows, and see a running credit total for what's selected.
// Each row has "Open in Builder" that jumps to the appropriate generator
// with the shot pre-selected via query params.

import { useEffect, useMemo, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import Link from 'next/link'
import { getSupabase } from '@/lib/auth'
import { showError, showSuccess } from '@/lib/notifications'
import { CAMPAIGN_FORMATS, getCampaignFormat } from '@/lib/campaign-formats'
import { ArrowLeft, Trash2, Loader2, Sparkles, ExternalLink, ChevronDown, ChevronRight, Wand2 } from 'lucide-react'
import type { CampaignFormat } from '@/lib/campaign-formats'

// Maps a campaign format to a short specific type badge so shots are
// scannable at a glance. Format-specific labels ("Editorial photo",
// "Studio still", "Carousel · 5", "Meme") beat generic category names.
function formatBadge(fmt: CampaignFormat | undefined): { label: string; bg: string; fg: string; border: string } {
  const green   = { bg: '#dcfce7', fg: '#166534', border: '#86efac' }
  const purple  = { bg: '#f3e8ff', fg: '#6b21a8', border: '#d8b4fe' }
  const amber   = { bg: '#fef3c7', fg: '#92400e', border: '#fcd34d' }
  const blue    = { bg: '#dbeafe', fg: '#1e40af', border: '#93c5fd' }
  const pink    = { bg: '#fce7f3', fg: '#9d174d', border: '#f9a8d4' }
  const gray    = { bg: 'var(--surface-2)', fg: 'var(--ink-2)', border: 'var(--border)' }
  if (!fmt) return { label: 'Shot', ...gray }
  // Per-key precise labels first
  const perKey: Record<string, string> = {
    'hero-editorial':      'Editorial photo',
    'studio-still':        'Studio still',
    'lifestyle-in-scene':  'Lifestyle photo',
    'carousel-instagram':  'Carousel',
    'single-post':         'Feed post',
    'meme-post':           'Meme post',
    'tv-spot':             'TV spot',
    'unboxing':            'Unboxing',
    'unboxing-asmr':       'ASMR unbox',
    'aesthetic-broll':     'B-roll',
    'product-showcase':    '360° showcase',
    'hyper-motion':        'Kinetic burst',
    'crush-test':          'Crush test',
    'mystery-box':         'Mystery box',
    'mess-to-fresh':       'Transform',
    'before-after':        'Before / after',
    'tutorial':            'Tutorial',
    'get-ready-with-me':   'GRWM',
    'camera-pov':          'POV shot',
    'pov-vlog':            'POV vlog',
    'interview-man-on-street': 'Street interview',
    'interview-pov':       'POV interview',
    'couple-sharing':      'Couple UGC',
    'roommate-rec':        'Roommate UGC',
  }
  const label = perKey[fmt.key] ?? fmt.label
  // Color by category
  if (fmt.category === 'photo')          return { label, ...green }
  if (fmt.category === 'social')         return { label, ...pink }
  if (fmt.category === 'motion')         return { label, ...purple }
  if (fmt.category === 'transformation') return { label, ...amber }
  if (fmt.category === 'two-person')     return { label, ...blue }
  return { label, ...blue }
}

interface Campaign {
  id: string
  name: string
  brief: string | null
  product_id: string | null
  goal: string | null
  duration_label: string | null
  status: string
  meta: Record<string, unknown>
  created_at: string
}

interface Shot {
  id: string
  campaign_id: string
  position: number
  format_key: string
  pipeline: string
  spec: {
    hook?: string
    script?: string
    cta?: string
    caption?: string
    setting?: string
    visual_notes?: string
    aspect?: string
    duration?: number
    notes?: string
    influencer_id?: string | null
    scene_id?: string | null
    rendered_video_url?: string | null
    rendered_video_id?: string | null
    rendered_at?: string | null
  }
  credit_hint: number
  selected: boolean
  status: string
  library_asset_id: string | null
  error: string | null
}

async function getToken(): Promise<string | null> {
  const supabase = getSupabase()
  if (!supabase) return null
  const { data } = await supabase.auth.getSession()
  return data.session?.access_token ?? null
}

// Compact aspect chip so the table stays tight.
const aspectOptions = ['9:16', '4:5', '1:1', '16:9'] as const

// Given a shot, return the URL to open the appropriate builder pre-filled.
// URL params carry the full content — we lean on sessionStorage on the
// landing page so query string length isn't a practical limit for our
// per-shot payloads (< 8 KB in every real case).
function builderUrl(shot: Shot, productId: string | null, campaignId: string, productName?: string | null): string {
  const params = new URLSearchParams({ campaign: campaignId, shot: shot.id })
  if (productId) params.set('product', productId)
  if (productName) params.set('productName', productName)
  if (shot.spec.aspect) params.set('aspect', shot.spec.aspect)
  if (shot.spec.duration) params.set('duration', String(shot.spec.duration))
  if (shot.spec.hook) params.set('hook', shot.spec.hook)
  if (shot.spec.setting) params.set('setting', shot.spec.setting)
  if (shot.spec.script) params.set('script', shot.spec.script.slice(0, 2000))
  if (shot.spec.cta) params.set('cta', shot.spec.cta.slice(0, 200))
  if (shot.spec.visual_notes) params.set('visualNotes', shot.spec.visual_notes.slice(0, 800))
  if (shot.spec.caption) params.set('caption', shot.spec.caption.slice(0, 500))
  if (shot.spec.influencer_id) params.set('actor', shot.spec.influencer_id)
  if (shot.spec.scene_id) params.set('scene', shot.spec.scene_id)
  const fmt = getCampaignFormat(shot.format_key)
  params.set('format', shot.format_key)
  if (fmt?.label) params.set('formatLabel', fmt.label)
  // Route each pipeline to the builder that owns the render. ProductStudio
  // reads mode/substyle/productName/productDescription — set them here so
  // the shot lands with the shoot direction already dialed in.
  switch (shot.pipeline) {
    case 'ugc-video':
    case 'ugc-interview':
    case 'ugc-couple':
    case 'motion-broll':
      return `/generate/ugc?${params.toString()}`
    case 'product-photo':
      params.set('mode', 'aesthetic')
      params.set('substyle', 'studio')
      return `/generate/products?${params.toString()}`
    case 'lifestyle-photo':
      params.set('mode', 'aesthetic')
      params.set('substyle', 'lifestyle')
      return `/generate/products?${params.toString()}`
    case 'hero-editorial':
      // Hero editorial routes to Product Studio too — it's a product hero
      // and Product Studio has the reference-sheet workflow that keeps
      // the product consistent across shots.
      params.set('mode', 'aesthetic')
      params.set('substyle', 'editorial')
      return `/generate/products?${params.toString()}`
    case 'social-carousel':
      params.set('mode', 'carousel')
      return `/generate/social?${params.toString()}`
    case 'social-post':
      params.set('mode', 'post')
      return `/generate/social?${params.toString()}`
    default:
      return `/generate/ugc?${params.toString()}`
  }
}

export default function CampaignDetailPage() {
  const params = useParams<{ id: string }>()
  const router = useRouter()
  const campaignId = params?.id as string
  const [campaign, setCampaign] = useState<Campaign | null>(null)
  const [shots, setShots] = useState<Shot[]>([])
  const [loading, setLoading] = useState(true)
  const [savingIds, setSavingIds] = useState<Set<string>>(new Set())
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set())

  function toggleExpanded(id: string) {
    setExpandedIds(prev => {
      const n = new Set(prev)
      if (n.has(id)) n.delete(id); else n.add(id)
      return n
    })
  }

  useEffect(() => {
    void (async () => {
      const token = await getToken()
      if (!token) { setLoading(false); return }
      const res = await fetch(`/api/campaigns/${campaignId}`, { headers: { Authorization: `Bearer ${token}` } })
      if (!res.ok) { showError('Failed to load campaign'); setLoading(false); return }
      const data = await res.json()
      setCampaign(data.campaign)
      setShots(data.shots ?? [])
      setLoading(false)
    })()
  }, [campaignId])

  const selectedShots = useMemo(() => shots.filter(s => s.selected), [shots])
  const totalCredits = useMemo(() => selectedShots.reduce((sum, s) => sum + (s.credit_hint ?? 0), 0), [selectedShots])

  async function patchShot(shotId: string, body: Record<string, unknown>) {
    const token = await getToken()
    if (!token) return
    setSavingIds(prev => new Set(prev).add(shotId))
    try {
      const res = await fetch(`/api/campaigns/${campaignId}/shots/${shotId}`, {
        method: 'PATCH',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      if (!res.ok) showError('Save failed')
    } finally {
      setSavingIds(prev => { const n = new Set(prev); n.delete(shotId); return n })
    }
  }

  function updateSpec(shotId: string, key: keyof Shot['spec'], value: string | number) {
    setShots(prev => prev.map(s => s.id === shotId ? { ...s, spec: { ...s.spec, [key]: value } } : s))
  }

  async function commitSpec(shot: Shot, key: keyof Shot['spec'], value: string | number) {
    // Duration changes rescale credits proportionally.
    if (key === 'duration' && typeof value === 'number') {
      const fmt = getCampaignFormat(shot.format_key)
      if (fmt && fmt.defaultDuration > 0) {
        const newCredits = Math.max(1, Math.round(fmt.creditHint * value / fmt.defaultDuration))
        setShots(prev => prev.map(s => s.id === shot.id ? { ...s, credit_hint: newCredits } : s))
        await patchShot(shot.id, { spec: { [key]: value }, credit_hint: newCredits })
        return
      }
    }
    await patchShot(shot.id, { spec: { [key]: value } })
  }

  async function toggleSelected(shot: Shot) {
    const next = !shot.selected
    setShots(prev => prev.map(s => s.id === shot.id ? { ...s, selected: next } : s))
    await patchShot(shot.id, { selected: next })
  }

  async function deleteShot(shot: Shot) {
    if (!confirm('Delete this shot?')) return
    const token = await getToken()
    if (!token) return
    const res = await fetch(`/api/campaigns/${campaignId}/shots/${shot.id}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    })
    if (res.ok) setShots(prev => prev.filter(s => s.id !== shot.id))
  }

  async function deleteCampaign() {
    if (!confirm('Delete this campaign and all its shots?')) return
    const token = await getToken()
    if (!token) return
    await fetch(`/api/campaigns/${campaignId}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    })
    showSuccess('Campaign deleted')
    router.push('/campaigns')
  }

  async function enrichShot(shot: Shot) {
    const token = await getToken()
    if (!token) return
    setSavingIds(prev => new Set(prev).add(shot.id))
    try {
      const res = await fetch(`/api/campaigns/${campaignId}/shots/${shot.id}/enrich`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` },
      })
      if (!res.ok) { showError('Enrichment failed'); return }
      const data = await res.json()
      setShots(prev => prev.map(s => s.id === shot.id ? { ...s, spec: { ...s.spec, ...data.spec } } : s))
      showSuccess('Script + CTA + visual notes generated')
    } finally {
      setSavingIds(prev => { const n = new Set(prev); n.delete(shot.id); return n })
    }
  }

  function selectAll(v: boolean) {
    setShots(prev => prev.map(s => ({ ...s, selected: v })))
    // Batch fire updates (best-effort, no await).
    for (const s of shots) if (s.selected !== v) void patchShot(s.id, { selected: v })
  }

  const [expanding, setExpanding] = useState(false)
  async function expandCampaign() {
    setExpanding(true)
    const token = await getToken()
    if (!token) { setExpanding(false); return }
    try {
      const res = await fetch(`/api/campaigns/${campaignId}/expand`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` },
      })
      if (!res.ok) { const d = await res.json().catch(() => ({} as { error?: string })); showError(d.error ?? 'Expand failed'); return }
      const r2 = await fetch(`/api/campaigns/${campaignId}`, { headers: { Authorization: `Bearer ${token}` } })
      const data = await r2.json()
      setCampaign(data.campaign)
      setShots(data.shots ?? [])
      showSuccess('Expanded to a full campaign')
    } finally {
      setExpanding(false)
    }
  }

  if (loading) {
    return <div style={{ padding: 40, display: 'flex', gap: 10, alignItems: 'center', color: 'var(--ink-2)' }}><Loader2 size={16} className="animate-spin" /> Loading campaign…</div>
  }
  if (!campaign) {
    return <div style={{ padding: 40 }}>Campaign not found. <Link href="/campaigns">Back</Link></div>
  }

  return (
    <div style={{ padding: '28px 32px', maxWidth: 1400, margin: '0 auto' }}>
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <Link href="/campaigns" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 13, color: 'var(--ink-2)', textDecoration: 'none', marginBottom: 10 }}>
          <ArrowLeft size={14} /> All campaigns
        </Link>
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 20 }}>
          <div>
            <h1 style={{ fontSize: 30, fontWeight: 700, margin: '0 0 6px' }}>{campaign.name}</h1>
            <div style={{ fontSize: 13, color: 'var(--ink-2)' }}>
              {campaign.goal ? campaign.goal + ' · ' : ''}{campaign.duration_label ?? ''} · {shots.length} shots planned
            </div>
            {campaign.brief && (
              <div style={{ marginTop: 12, padding: '10px 14px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, color: 'var(--ink-2)', maxWidth: 900 }}>
                <strong style={{ color: 'var(--ink)' }}>Brief:</strong> {campaign.brief}
              </div>
            )}
            {Array.isArray((campaign.meta as { trend_sources?: unknown }).trend_sources) && ((campaign.meta as { trend_sources: unknown[] }).trend_sources.length > 0) && (
              <details style={{ marginTop: 12, maxWidth: 900 }}>
                <summary style={{ fontSize: 12, color: 'var(--ink-2)', cursor: 'pointer', userSelect: 'none' }}>
                  <strong style={{ color: 'var(--ink)' }}>Sources ({(campaign.meta as { trend_sources: unknown[] }).trend_sources.length})</strong> — auto-discovered trend + competitor references Sonnet used
                </summary>
                <div style={{ marginTop: 8, padding: '10px 14px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 8, fontSize: 12.5, display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {((campaign.meta as { trend_sources: Array<{ url: string; title: string; query: string }> }).trend_sources).map((s, i) => (
                    <a key={i} href={s.url} target="_blank" rel="noopener noreferrer" style={{ color: 'var(--ink)', textDecoration: 'none', display: 'block' }}>
                      <div style={{ fontWeight: 600 }}>{s.title || s.url}</div>
                      <div style={{ fontSize: 11.5, color: 'var(--ink-2)' }}>{s.query} → {new URL(s.url).host}</div>
                    </a>
                  ))}
                </div>
              </details>
            )}
          </div>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <Link
              href={`/library?campaign=${campaign.id}`}
              className="btn btn-ghost"
              style={{ fontSize: 13, display: 'inline-flex', alignItems: 'center', gap: 6 }}
            >
              <ExternalLink size={14} /> View in Library
            </Link>
            <button onClick={deleteCampaign} className="btn btn-ghost" style={{ color: '#c33', fontSize: 13 }}>
              <Trash2 size={14} /> Delete
            </button>
          </div>
        </div>
      </div>

      {/* Expand preview banner — for campaigns created via the onboarding lite planner */}
      {(campaign.meta as { source?: string; expandable?: boolean }).source === 'onboarding' && (campaign.meta as { expandable?: boolean }).expandable && (
        <div style={{ marginBottom: 14, padding: '14px 16px', background: '#fef3c7', border: '1px solid #fde68a', borderRadius: 10, display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap' }}>
          <div style={{ flex: 1, minWidth: 200 }}>
            <div style={{ fontSize: 13.5, fontWeight: 700, color: '#78350f', marginBottom: 2 }}>This is your preview campaign — expand it into a full 2-week plan.</div>
            <div style={{ fontSize: 12.5, color: '#92400e' }}>Sonnet will draft 18 more diverse shots to round it out. Your existing 6 stay untouched.</div>
          </div>
          <button
            onClick={expandCampaign}
            disabled={expanding}
            className="btn btn-primary"
            style={{ fontSize: 13, padding: '9px 16px', display: 'inline-flex', alignItems: 'center', gap: 6 }}
          >
            {expanding ? <><Loader2 size={14} className="animate-spin" /> Expanding…</> : <><Sparkles size={14} /> Expand to full campaign</>}
          </button>
        </div>
      )}

      {/* Research summary — Sonnet's short French-language bilan on what it learned from sources */}
      {typeof (campaign.meta as { research_summary?: string }).research_summary === 'string' && (campaign.meta as { research_summary: string }).research_summary.trim() && (
        <div style={{ marginBottom: 14, padding: '14px 16px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 10 }}>
          <div style={{ fontSize: 10.5, fontWeight: 700, letterSpacing: 0.6, color: 'var(--ink-2)', marginBottom: 8, textTransform: 'uppercase' }}>Bilan de la recherche</div>
          <div style={{ fontSize: 13.5, lineHeight: 1.55, color: 'var(--ink)', whiteSpace: 'pre-wrap' }}>
            {(campaign.meta as { research_summary: string }).research_summary}
          </div>
        </div>
      )}

      {/* Totals bar */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '12px 16px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 10, marginBottom: 14, flexWrap: 'wrap' }}>
        <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, cursor: 'pointer' }}>
          <input
            type="checkbox"
            checked={selectedShots.length === shots.length && shots.length > 0}
            onChange={e => selectAll(e.target.checked)}
          />
          Select all
        </label>
        <div style={{ fontSize: 13, color: 'var(--ink-2)' }}>
          <strong style={{ color: 'var(--ink)' }}>{selectedShots.length}</strong> selected
        </div>
        <button
          className="btn btn-ghost"
          onClick={() => {
            if (expandedIds.size === shots.length) setExpandedIds(new Set())
            else setExpandedIds(new Set(shots.map(s => s.id)))
          }}
          style={{ fontSize: 12.5 }}
        >
          {expandedIds.size === shots.length ? 'Collapse all' : 'Expand all'}
        </button>
        <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{ fontSize: 13, color: 'var(--ink-2)' }}>
            Estimated total: <strong style={{ color: 'var(--ink)', fontSize: 15 }}>{totalCredits.toLocaleString()} cr</strong>
          </div>
        </div>
      </div>

      {/* Cards */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {shots.map(shot => {
          const fmt = getCampaignFormat(shot.format_key)
          const saving = savingIds.has(shot.id)
          const isPhoto = (fmt?.defaultDuration ?? 0) === 0
          const isExpanded = expandedIds.has(shot.id)
          return (
            <div
              key={shot.id}
              style={{
                background: 'var(--surface)',
                border: `1.5px solid ${shot.selected ? 'var(--ink)' : 'var(--border)'}`,
                borderRadius: 12,
                padding: isExpanded ? 16 : 12,
                opacity: shot.selected ? 1 : 0.6,
                transition: 'opacity 0.15s, border-color 0.15s, padding 0.15s',
              }}
            >
              {/* Header row — clicking the label area expands/collapses */}
              <div
                style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap', marginBottom: isExpanded ? 14 : 0, cursor: 'pointer' }}
                onClick={e => {
                  // Don't toggle when clicking any interactive control inside the row.
                  const el = e.target as HTMLElement
                  if (el.closest('input, select, button, a, textarea, label')) return
                  toggleExpanded(shot.id)
                }}
              >
                <input type="checkbox" checked={shot.selected} onChange={() => toggleSelected(shot)} style={{ width: 16, height: 16, cursor: 'pointer' }} />
                <div style={{ fontSize: 12, color: 'var(--ink-2)', fontWeight: 600, minWidth: 24 }}>#{shot.position}</div>
                <button
                  onClick={() => toggleExpanded(shot.id)}
                  className="btn btn-ghost"
                  style={{ padding: 4, display: 'inline-flex' }}
                  title={isExpanded ? 'Collapse' : 'Expand'}
                >
                  {isExpanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                </button>
                <div style={{ flex: 1, minWidth: 200 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
                    <div style={{ fontSize: 15, fontWeight: 700 }}>{fmt?.label ?? shot.format_key}</div>
                    {(() => {
                      const badge = formatBadge(fmt)
                      return (
                        <span style={{
                          fontSize: 10.5, fontWeight: 700, letterSpacing: 0.3,
                          textTransform: 'uppercase',
                          padding: '2px 7px', borderRadius: 999,
                          background: badge.bg, color: badge.fg,
                          border: `1px solid ${badge.border}`,
                          whiteSpace: 'nowrap',
                        }}>{badge.label}</span>
                      )
                    })()}
                  </div>
                  <div style={{ fontSize: 12, color: 'var(--ink-2)', marginTop: 3 }}>{fmt?.tagline ?? shot.pipeline}</div>
                </div>

                {/* Aspect chip */}
                <label style={chipLabel}>
                  <span style={chipKey}>Aspect</span>
                  <select
                    value={shot.spec.aspect ?? fmt?.defaultAspect ?? '9:16'}
                    onChange={e => { updateSpec(shot.id, 'aspect', e.target.value); void commitSpec(shot, 'aspect', e.target.value) }}
                    style={chipInput}
                  >
                    {aspectOptions.map(a => <option key={a} value={a}>{a}</option>)}
                  </select>
                </label>

                {/* Duration chip (only for video formats) */}
                {!isPhoto && (
                  <label style={chipLabel}>
                    <span style={chipKey}>Duration</span>
                    <input
                      type="number"
                      min={4} max={30}
                      value={shot.spec.duration ?? fmt?.defaultDuration ?? 0}
                      onChange={e => updateSpec(shot.id, 'duration', Number(e.target.value))}
                      onBlur={e => commitSpec(shot, 'duration', Number(e.target.value))}
                      style={{ ...chipInput, width: 50, textAlign: 'center' }}
                    />
                    <span style={{ fontSize: 11.5, color: 'var(--ink-2)' }}>s</span>
                  </label>
                )}

                {/* Credits chip */}
                <div style={{ ...chipLabel, background: 'var(--surface-2)' }}>
                  <span style={chipKey}>Credits</span>
                  <span style={{ fontSize: 13, fontWeight: 700 }}>{shot.credit_hint}</span>
                </div>

                {/* Rendered badge */}
                {shot.status === 'done' && (
                  <div style={{ ...chipLabel, background: '#dcfce7', border: '1px solid #86efac', color: '#166534' }}>
                    <span style={{ ...chipKey, color: '#166534' }}>Rendered</span>
                    {shot.spec.rendered_video_url && (
                      <a href={shot.spec.rendered_video_url} target="_blank" rel="noopener noreferrer" style={{ color: '#166534', textDecoration: 'underline', fontSize: 12 }}>
                        watch ↗
                      </a>
                    )}
                  </div>
                )}

                {/* Actions */}
                <div style={{ display: 'flex', gap: 4, alignItems: 'center' }}>
                  {saving && <Loader2 size={13} className="animate-spin" style={{ color: 'var(--ink-2)' }} />}
                  <Link
                    href={builderUrl(shot, campaign.product_id, campaign.id, (campaign.meta as { product_name?: string })?.product_name ?? null)}
                    className="btn btn-ghost"
                    style={{ padding: '6px 10px', fontSize: 12, gap: 5, display: 'inline-flex', alignItems: 'center' }}
                    title="Open in Builder"
                  >
                    <ExternalLink size={13} /> Builder
                  </Link>
                  <button
                    onClick={() => deleteShot(shot)}
                    className="btn btn-ghost"
                    style={{ padding: '6px 8px', color: '#c33' }}
                    title="Delete shot"
                  >
                    <Trash2 size={13} />
                  </button>
                </div>
              </div>

              {/* Editable fields — grouped by function */}
              {isExpanded && (<>
              {/* Format info panel — tells the user what this format is,
                  what it needs, and where clicking Builder will take them. */}
              {fmt && (
                <div style={{
                  display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 0,
                  marginBottom: 14,
                  border: '1px solid var(--border)', borderRadius: 10,
                  overflow: 'hidden', background: 'var(--surface-2)',
                }}>
                  <InfoCell label="Category" value={fmt.category.replace(/-/g, ' ')} />
                  <InfoCell label="Pipeline" value={pipelineLabel(fmt.pipeline)} />
                  <InfoCell label="Renders in" value={pipelineTarget(fmt.pipeline)} last />
                  <InfoCell label="Needs actor" value={fmt.requiresActor ? 'Yes' : 'No'} />
                  <InfoCell label="Needs scene" value={fmt.requiresScene ? 'Yes' : 'No'} />
                  <InfoCell label="Needs product" value={fmt.requiresProduct ? 'Yes' : 'No'} last />
                  <InfoCell
                    label="Base spec"
                    value={`${fmt.defaultAspect} · ${fmt.defaultDuration > 0 ? `${fmt.defaultDuration}s` : 'still'}`}
                  />
                  <InfoCell label="Est. credits" value={`${shot.credit_hint} cr`} />
                  <InfoCell label="Status" value={shot.status === 'done' ? 'Rendered ✓' : (shot.spec.script ? 'Script drafted' : 'Planned')} last />
                </div>
              )}

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 12 }}>
                <FieldBlock label="Hook">
                  <textarea
                    value={shot.spec.hook ?? ''}
                    onChange={e => updateSpec(shot.id, 'hook', e.target.value)}
                    onBlur={e => commitSpec(shot, 'hook', e.target.value)}
                    rows={2}
                    style={roomyInput}
                  />
                </FieldBlock>
                <FieldBlock label="Setting">
                  <textarea
                    value={shot.spec.setting ?? ''}
                    onChange={e => updateSpec(shot.id, 'setting', e.target.value)}
                    onBlur={e => commitSpec(shot, 'setting', e.target.value)}
                    rows={2}
                    style={roomyInput}
                  />
                </FieldBlock>
              </div>

              <div style={{ marginBottom: 12 }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 5 }}>
                  <div style={{ fontSize: 10.5, fontWeight: 700, letterSpacing: 0.6, color: 'var(--ink-2)', textTransform: 'uppercase' }}>Script / Dialogue</div>
                  {!shot.spec.script && (
                    <button
                      onClick={() => enrichShot(shot)}
                      disabled={saving}
                      className="btn btn-ghost"
                      style={{ padding: '4px 10px', fontSize: 11.5, display: 'inline-flex', gap: 5, alignItems: 'center' }}
                      title="Generate script + CTA + visual notes with Haiku"
                    >
                      {saving ? <Loader2 size={12} className="animate-spin" /> : <Wand2 size={12} />} Generate
                    </button>
                  )}
                </div>
                <textarea
                  value={shot.spec.script ?? ''}
                  onChange={e => updateSpec(shot.id, 'script', e.target.value)}
                  onBlur={e => commitSpec(shot, 'script', e.target.value)}
                  rows={5}
                  placeholder="Click Generate to have AI draft the full dialogue for this shot."
                  style={{ ...roomyInput, minHeight: 130, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: 13 }}
                />
              </div>

              <div style={{ marginBottom: 12 }}>
                <FieldBlock label="Visual notes / Beats">
                  <textarea
                    value={shot.spec.visual_notes ?? ''}
                    onChange={e => updateSpec(shot.id, 'visual_notes', e.target.value)}
                    onBlur={e => commitSpec(shot, 'visual_notes', e.target.value)}
                    rows={2}
                    style={roomyInput}
                  />
                </FieldBlock>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 12 }}>
                <FieldBlock label="CTA">
                  <textarea
                    value={shot.spec.cta ?? ''}
                    onChange={e => updateSpec(shot.id, 'cta', e.target.value)}
                    onBlur={e => commitSpec(shot, 'cta', e.target.value)}
                    rows={2}
                    style={roomyInput}
                  />
                </FieldBlock>
                <FieldBlock label="Caption (on-post copy)">
                  <textarea
                    value={shot.spec.caption ?? ''}
                    onChange={e => updateSpec(shot.id, 'caption', e.target.value)}
                    onBlur={e => commitSpec(shot, 'caption', e.target.value)}
                    rows={2}
                    style={roomyInput}
                  />
                </FieldBlock>
              </div>

              {/* Prominent bottom Builder CTA — the primary action once
                  the shot spec is dialed in. */}
              <div style={{
                marginTop: 14, paddingTop: 14, borderTop: '1px solid var(--border)',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12,
              }}>
                <div style={{ fontSize: 12, color: 'var(--ink-2)' }}>
                  {shot.spec.script
                    ? <>Script is ready — open the Builder to render this shot.</>
                    : <>Add a script (Generate above) or open the Builder to draft in place.</>}
                </div>
                <Link
                  href={builderUrl(shot, campaign.product_id, campaign.id, (campaign.meta as { product_name?: string })?.product_name ?? null)}
                  className="btn btn-primary"
                  style={{ padding: '9px 16px', fontSize: 13, gap: 6, display: 'inline-flex', alignItems: 'center' }}
                >
                  <ExternalLink size={14} /> Open in {pipelineTarget(fmt?.pipeline ?? 'ugc-video')}
                </Link>
              </div>
              </>)}
            </div>
          )
        })}
      </div>

      {shots.length === 0 && (
        <div style={{ textAlign: 'center', padding: 40, color: 'var(--ink-2)' }}>
          No shots yet.
        </div>
      )}
    </div>
  )
}

function InfoCell({ label, value, last }: { label: string; value: string; last?: boolean }) {
  return (
    <div style={{
      padding: '10px 14px',
      borderRight: last ? 'none' : '1px solid var(--border)',
      borderTop: '1px solid var(--border)',
      background: 'var(--surface)',
    }}>
      <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 0.6, color: 'var(--ink-2)', textTransform: 'uppercase' }}>{label}</div>
      <div style={{ fontSize: 13, fontWeight: 600, marginTop: 3, textTransform: 'capitalize' }}>{value}</div>
    </div>
  )
}

function pipelineLabel(pipeline: string): string {
  switch (pipeline) {
    case 'ugc-video':       return 'UGC video (single actor)'
    case 'ugc-interview':   return 'UGC interview (two-person)'
    case 'ugc-couple':      return 'UGC couple / friends'
    case 'motion-broll':    return 'Product B-roll (motion, no dialogue)'
    case 'product-photo':   return 'Product photo (clean plate)'
    case 'lifestyle-photo': return 'Lifestyle photo (in-scene)'
    case 'hero-editorial':  return 'Editorial hero image'
    case 'social-carousel': return 'Multi-slide social carousel'
    case 'social-post':     return 'Single social post'
    default:                return pipeline
  }
}

function pipelineTarget(pipeline: string): string {
  switch (pipeline) {
    case 'ugc-video':
    case 'ugc-interview':
    case 'ugc-couple':
    case 'motion-broll':    return 'UGC Studio'
    case 'product-photo':
    case 'lifestyle-photo':
    case 'hero-editorial':  return 'Product Studio'
    case 'social-carousel':
    case 'social-post':     return 'Social Studio'
    default:                return 'Builder'
  }
}

function FieldBlock({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div style={{ fontSize: 10.5, fontWeight: 700, letterSpacing: 0.6, color: 'var(--ink-2)', marginBottom: 5, textTransform: 'uppercase' }}>{label}</div>
      {children}
    </div>
  )
}

const roomyInput: React.CSSProperties = {
  width: '100%',
  padding: '10px 12px',
  fontSize: 13.5,
  lineHeight: 1.5,
  fontFamily: 'inherit',
  border: '1px solid var(--border)',
  borderRadius: 8,
  background: 'var(--surface-2)',
  color: 'var(--ink)',
  resize: 'vertical',
  minHeight: 82,
}

const chipLabel: React.CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  gap: 6,
  padding: '5px 10px',
  border: '1px solid var(--border)',
  borderRadius: 8,
  background: 'var(--surface)',
  fontSize: 12,
}

const chipKey: React.CSSProperties = {
  fontSize: 10.5,
  fontWeight: 700,
  color: 'var(--ink-2)',
  textTransform: 'uppercase',
  letterSpacing: 0.5,
}

const chipInput: React.CSSProperties = {
  padding: '3px 6px',
  fontSize: 12.5,
  fontFamily: 'inherit',
  border: 'none',
  background: 'transparent',
  color: 'var(--ink)',
  outline: 'none',
}

