'use client'

// Campaign detail — inline-editable shot table generated by the Campaign
// Planner. User can tick/untick, edit hook/caption/setting/duration/aspect
// in place, delete rows, and see a running credit total for what's selected.
// Each row has "Open in Builder" that jumps to the appropriate generator
// with the shot pre-selected via query params.

import { useEffect, useMemo, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import Link from 'next/link'
import { getSupabase } from '@/lib/auth'
import { showError, showSuccess } from '@/lib/notifications'
import { CAMPAIGN_FORMATS, getCampaignFormat } from '@/lib/campaign-formats'
import { ArrowLeft, Trash2, Loader2, Sparkles, ExternalLink } from 'lucide-react'

interface Campaign {
  id: string
  name: string
  brief: string | null
  product_id: string | null
  goal: string | null
  duration_label: string | null
  status: string
  meta: Record<string, unknown>
  created_at: string
}

interface Shot {
  id: string
  campaign_id: string
  position: number
  format_key: string
  pipeline: string
  spec: {
    hook?: string
    caption?: string
    setting?: string
    aspect?: string
    duration?: number
    notes?: string
    influencer_id?: string | null
    scene_id?: string | null
  }
  credit_hint: number
  selected: boolean
  status: string
  library_asset_id: string | null
  error: string | null
}

async function getToken(): Promise<string | null> {
  const supabase = getSupabase()
  if (!supabase) return null
  const { data } = await supabase.auth.getSession()
  return data.session?.access_token ?? null
}

// Compact aspect chip so the table stays tight.
const aspectOptions = ['9:16', '4:5', '1:1', '16:9'] as const

// Given a shot, return the URL to open the appropriate builder pre-filled.
function builderUrl(shot: Shot, productId: string | null, campaignId: string): string {
  const params = new URLSearchParams({ campaign: campaignId, shot: shot.id })
  if (productId) params.set('product', productId)
  if (shot.spec.aspect) params.set('aspect', shot.spec.aspect)
  if (shot.spec.duration) params.set('duration', String(shot.spec.duration))
  if (shot.spec.hook) params.set('hook', shot.spec.hook)
  if (shot.spec.setting) params.set('setting', shot.spec.setting)
  if (shot.spec.influencer_id) params.set('actor', shot.spec.influencer_id)
  if (shot.spec.scene_id) params.set('scene', shot.spec.scene_id)
  params.set('format', shot.format_key)
  switch (shot.pipeline) {
    case 'ugc-video':
    case 'ugc-interview':
    case 'ugc-couple':
    case 'motion-broll':
      return `/generate/ugc?${params.toString()}`
    case 'product-photo':
    case 'lifestyle-photo':
      return `/generate/products?${params.toString()}`
    case 'hero-editorial':
      return `/generate/image?${params.toString()}`
    default:
      return `/generate/ugc?${params.toString()}`
  }
}

export default function CampaignDetailPage() {
  const params = useParams<{ id: string }>()
  const router = useRouter()
  const campaignId = params?.id as string
  const [campaign, setCampaign] = useState<Campaign | null>(null)
  const [shots, setShots] = useState<Shot[]>([])
  const [loading, setLoading] = useState(true)
  const [savingIds, setSavingIds] = useState<Set<string>>(new Set())

  useEffect(() => {
    void (async () => {
      const token = await getToken()
      if (!token) { setLoading(false); return }
      const res = await fetch(`/api/campaigns/${campaignId}`, { headers: { Authorization: `Bearer ${token}` } })
      if (!res.ok) { showError('Failed to load campaign'); setLoading(false); return }
      const data = await res.json()
      setCampaign(data.campaign)
      setShots(data.shots ?? [])
      setLoading(false)
    })()
  }, [campaignId])

  const selectedShots = useMemo(() => shots.filter(s => s.selected), [shots])
  const totalCredits = useMemo(() => selectedShots.reduce((sum, s) => sum + (s.credit_hint ?? 0), 0), [selectedShots])

  async function patchShot(shotId: string, body: Record<string, unknown>) {
    const token = await getToken()
    if (!token) return
    setSavingIds(prev => new Set(prev).add(shotId))
    try {
      const res = await fetch(`/api/campaigns/${campaignId}/shots/${shotId}`, {
        method: 'PATCH',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })
      if (!res.ok) showError('Save failed')
    } finally {
      setSavingIds(prev => { const n = new Set(prev); n.delete(shotId); return n })
    }
  }

  function updateSpec(shotId: string, key: keyof Shot['spec'], value: string | number) {
    setShots(prev => prev.map(s => s.id === shotId ? { ...s, spec: { ...s.spec, [key]: value } } : s))
  }

  async function commitSpec(shot: Shot, key: keyof Shot['spec'], value: string | number) {
    await patchShot(shot.id, { spec: { [key]: value } })
  }

  async function toggleSelected(shot: Shot) {
    const next = !shot.selected
    setShots(prev => prev.map(s => s.id === shot.id ? { ...s, selected: next } : s))
    await patchShot(shot.id, { selected: next })
  }

  async function deleteShot(shot: Shot) {
    if (!confirm('Delete this shot?')) return
    const token = await getToken()
    if (!token) return
    const res = await fetch(`/api/campaigns/${campaignId}/shots/${shot.id}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    })
    if (res.ok) setShots(prev => prev.filter(s => s.id !== shot.id))
  }

  async function deleteCampaign() {
    if (!confirm('Delete this campaign and all its shots?')) return
    const token = await getToken()
    if (!token) return
    await fetch(`/api/campaigns/${campaignId}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` },
    })
    showSuccess('Campaign deleted')
    router.push('/campaigns')
  }

  function selectAll(v: boolean) {
    setShots(prev => prev.map(s => ({ ...s, selected: v })))
    // Batch fire updates (best-effort, no await).
    for (const s of shots) if (s.selected !== v) void patchShot(s.id, { selected: v })
  }

  if (loading) {
    return <div style={{ padding: 40, display: 'flex', gap: 10, alignItems: 'center', color: 'var(--ink-2)' }}><Loader2 size={16} className="spin" /> Loading campaign…</div>
  }
  if (!campaign) {
    return <div style={{ padding: 40 }}>Campaign not found. <Link href="/campaigns">Back</Link></div>
  }

  return (
    <div style={{ padding: '28px 32px', maxWidth: 1400, margin: '0 auto' }}>
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <Link href="/campaigns" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 13, color: 'var(--ink-2)', textDecoration: 'none', marginBottom: 10 }}>
          <ArrowLeft size={14} /> All campaigns
        </Link>
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 20 }}>
          <div>
            <h1 style={{ fontSize: 30, fontWeight: 700, margin: '0 0 6px' }}>{campaign.name}</h1>
            <div style={{ fontSize: 13, color: 'var(--ink-2)' }}>
              {campaign.goal ? campaign.goal + ' · ' : ''}{campaign.duration_label ?? ''} · {shots.length} shots planned
            </div>
            {campaign.brief && (
              <div style={{ marginTop: 12, padding: '10px 14px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 8, fontSize: 13, color: 'var(--ink-2)', maxWidth: 900 }}>
                <strong style={{ color: 'var(--ink)' }}>Brief:</strong> {campaign.brief}
              </div>
            )}
          </div>
          <button onClick={deleteCampaign} className="btn btn-ghost" style={{ color: '#c33', fontSize: 13 }}>
            <Trash2 size={14} /> Delete
          </button>
        </div>
      </div>

      {/* Totals bar */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '12px 16px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 10, marginBottom: 14, flexWrap: 'wrap' }}>
        <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, cursor: 'pointer' }}>
          <input
            type="checkbox"
            checked={selectedShots.length === shots.length && shots.length > 0}
            onChange={e => selectAll(e.target.checked)}
          />
          Select all
        </label>
        <div style={{ fontSize: 13, color: 'var(--ink-2)' }}>
          <strong style={{ color: 'var(--ink)' }}>{selectedShots.length}</strong> selected
        </div>
        <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 12 }}>
          <div style={{ fontSize: 13, color: 'var(--ink-2)' }}>
            Estimated total: <strong style={{ color: 'var(--ink)', fontSize: 15 }}>{totalCredits.toLocaleString()} cr</strong>
          </div>
        </div>
      </div>

      {/* Table */}
      <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 10, overflow: 'hidden' }}>
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              <tr style={{ background: 'var(--surface-2)', borderBottom: '1px solid var(--border)', textAlign: 'left', color: 'var(--ink-2)', fontSize: 11.5, letterSpacing: 0.4, textTransform: 'uppercase' }}>
                <th style={{ padding: '10px 8px', width: 32 }}></th>
                <th style={{ padding: '10px 8px', width: 30 }}>#</th>
                <th style={{ padding: '10px 8px', minWidth: 140 }}>Format</th>
                <th style={{ padding: '10px 8px', minWidth: 220 }}>Hook</th>
                <th style={{ padding: '10px 8px', minWidth: 160 }}>Setting</th>
                <th style={{ padding: '10px 8px', width: 70 }}>Aspect</th>
                <th style={{ padding: '10px 8px', width: 70 }}>Dur</th>
                <th style={{ padding: '10px 8px', minWidth: 220 }}>Caption</th>
                <th style={{ padding: '10px 8px', width: 70 }}>Credits</th>
                <th style={{ padding: '10px 8px', width: 120 }}></th>
              </tr>
            </thead>
            <tbody>
              {shots.map(shot => {
                const fmt = getCampaignFormat(shot.format_key)
                const saving = savingIds.has(shot.id)
                return (
                  <tr key={shot.id} style={{ borderBottom: '1px solid var(--border)', opacity: shot.selected ? 1 : 0.55 }}>
                    <td style={{ padding: '10px 8px' }}>
                      <input type="checkbox" checked={shot.selected} onChange={() => toggleSelected(shot)} />
                    </td>
                    <td style={{ padding: '10px 8px', color: 'var(--ink-2)' }}>{shot.position}</td>
                    <td style={{ padding: '10px 8px' }}>
                      <div style={{ fontWeight: 600 }}>{fmt?.label ?? shot.format_key}</div>
                      <div style={{ fontSize: 11.5, color: 'var(--ink-2)' }}>{fmt?.category ?? shot.pipeline}</div>
                    </td>
                    <td style={{ padding: '6px 8px' }}>
                      <textarea
                        value={shot.spec.hook ?? ''}
                        onChange={e => updateSpec(shot.id, 'hook', e.target.value)}
                        onBlur={e => commitSpec(shot, 'hook', e.target.value)}
                        rows={2}
                        style={inputStyle}
                      />
                    </td>
                    <td style={{ padding: '6px 8px' }}>
                      <textarea
                        value={shot.spec.setting ?? ''}
                        onChange={e => updateSpec(shot.id, 'setting', e.target.value)}
                        onBlur={e => commitSpec(shot, 'setting', e.target.value)}
                        rows={2}
                        style={inputStyle}
                      />
                    </td>
                    <td style={{ padding: '6px 8px' }}>
                      <select
                        value={shot.spec.aspect ?? fmt?.defaultAspect ?? '9:16'}
                        onChange={e => { updateSpec(shot.id, 'aspect', e.target.value); void commitSpec(shot, 'aspect', e.target.value) }}
                        style={selectStyle}
                      >
                        {aspectOptions.map(a => <option key={a} value={a}>{a}</option>)}
                      </select>
                    </td>
                    <td style={{ padding: '6px 8px' }}>
                      {(fmt?.defaultDuration ?? 0) > 0 ? (
                        <input
                          type="number"
                          min={4} max={30}
                          value={shot.spec.duration ?? fmt?.defaultDuration ?? 0}
                          onChange={e => updateSpec(shot.id, 'duration', Number(e.target.value))}
                          onBlur={e => commitSpec(shot, 'duration', Number(e.target.value))}
                          style={{ ...inputStyle, width: 55, textAlign: 'center' }}
                        />
                      ) : (
                        <span style={{ color: 'var(--ink-2)', fontSize: 12 }}>—</span>
                      )}
                    </td>
                    <td style={{ padding: '6px 8px' }}>
                      <textarea
                        value={shot.spec.caption ?? ''}
                        onChange={e => updateSpec(shot.id, 'caption', e.target.value)}
                        onBlur={e => commitSpec(shot, 'caption', e.target.value)}
                        rows={2}
                        style={inputStyle}
                      />
                    </td>
                    <td style={{ padding: '10px 8px', textAlign: 'center', fontWeight: 600, color: 'var(--ink-2)' }}>{shot.credit_hint}</td>
                    <td style={{ padding: '10px 8px' }}>
                      <div style={{ display: 'flex', gap: 6, alignItems: 'center', justifyContent: 'flex-end' }}>
                        {saving && <Loader2 size={12} className="spin" />}
                        <Link
                          href={builderUrl(shot, campaign.product_id, campaign.id)}
                          className="btn btn-ghost"
                          style={{ padding: '5px 8px', fontSize: 11.5 }}
                          title="Open in Builder"
                        >
                          <ExternalLink size={12} />
                        </Link>
                        <button
                          onClick={() => deleteShot(shot)}
                          className="btn btn-ghost"
                          style={{ padding: '5px 8px', fontSize: 11.5, color: '#c33' }}
                          title="Delete row"
                        >
                          <Trash2 size={12} />
                        </button>
                      </div>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </div>

      {shots.length === 0 && (
        <div style={{ textAlign: 'center', padding: 40, color: 'var(--ink-2)' }}>
          No shots yet.
        </div>
      )}
    </div>
  )
}

const inputStyle: React.CSSProperties = {
  width: '100%',
  padding: '6px 8px',
  fontSize: 12.5,
  fontFamily: 'inherit',
  border: '1px solid var(--border)',
  borderRadius: 6,
  background: 'var(--surface)',
  color: 'var(--ink)',
  resize: 'vertical',
  minHeight: 40,
  lineHeight: 1.35,
}

const selectStyle: React.CSSProperties = {
  padding: '6px 8px',
  fontSize: 12.5,
  border: '1px solid var(--border)',
  borderRadius: 6,
  background: 'var(--surface)',
  color: 'var(--ink)',
}
