'use client'

import { useState, useEffect } from 'react'
import ActorPicker from '@/components/ActorPicker'
import { EMPTY_CHARACTER, type CharacterProfile } from '@/components/CharacterBuilder'
import { LANGUAGES, DEFAULT_LANGUAGE_CODE } from '@/lib/languages'
import { ASPECTS, DEFAULT_ASPECT, type UGCAspect } from '@/lib/aspects'
import {
  DEFAULT_TIER,
  DEFAULT_DURATION,
  DURATION_OPTIONS,
  DURATION_CONFIGS,
  calculateVideoCredits,
  estimateRenderSeconds,
  creditsToUSD,
  type UGCTier,
  type UGCDuration,
} from '@/lib/tiers'
import { getSupabase } from '@/lib/auth'

interface HookVariant {
  id: string
  angle: string
  tone: string
  text: string
}

interface ShopifyProduct {
  id: number
  title: string
  handle: string
  body_html: string
  price: string
  images: string[]
}

interface UGCPackageBuilderProps {
  onGenerate: (settings: {
    ugcType: string
    tier: UGCTier
    duration: UGCDuration
    productName: string
    productDescription: string
    benefits: string
    callToAction: string
    style: string
    imageSize: string
    voiceId: string
    productImageBase64?: string
    productImageMimeType?: string
    selectedHook?: string
    character?: CharacterProfile
    customInstructions?: string
    language?: string
    aspect?: UGCAspect
    actorId?: string
    customPhotoBase64?: string
    customPhotoMimeType?: string
    productType?: 'physical' | 'software'
    prewrittenScript?: string
  }) => Promise<void>
  isLoading: boolean
  creditBalance: number
}

// The UGC builder always produces the full pipeline (script + Sora video +
// captions + B-rolls). For standalone images, users go to /generate/image
// from the sidebar — we don't conflate the two on this page anymore.
const UGC_TYPE = 'video-with-voiceover'

// Voice is now generated natively by Kling v3 omni-video (one model produces
// video + voice in perfect sync). No voice picker needed — Kling chooses the
// voice based on the character's appearance from the hero frame.

export default function UGCPackageBuilder({ onGenerate, isLoading, creditBalance }: UGCPackageBuilderProps) {
  // Single tier now — voice is generated by Kling natively, so the Standard/Hero
  // distinction is gone. `tier` kept in state purely as a constant for the API contract.
  const tier: UGCTier = DEFAULT_TIER
  const [duration, setDuration] = useState<UGCDuration>(DEFAULT_DURATION)
  const [productName, setProductName] = useState('')
  const [productDescription, setProductDescription] = useState('')
  const [benefits, setBenefits] = useState('')
  const [callToAction, setCallToAction] = useState('Try it today')
  const [customInstructions, setCustomInstructions] = useState('')
  const [language, setLanguage] = useState<string>(DEFAULT_LANGUAGE_CODE)
  const [aspect, setAspect] = useState<UGCAspect>(DEFAULT_ASPECT)
  const [character, setCharacter] = useState<CharacterProfile>(EMPTY_CHARACTER)
  const [actorId, setActorId] = useState<string | undefined>()
  const [customPhoto, setCustomPhoto] = useState<{ base64: string; mimeType: string } | undefined>()
  const [productImage, setProductImage] = useState<{ base64: string; mimeType: string; preview: string } | null>(null)
  const [productType, setProductType] = useState<'physical' | 'software'>('physical')

  // Shopify product picker
  const [shopifyUrl, setShopifyUrl] = useState('')
  const [shopifyProducts, setShopifyProducts] = useState<ShopifyProduct[] | null>(null)
  const [shopifyLoading, setShopifyLoading] = useState(false)
  const [shopifyError, setShopifyError] = useState<string | null>(null)
  const [selectedShopifyProduct, setSelectedShopifyProduct] = useState<ShopifyProduct | null>(null)

  // Brand profile — loaded once on mount. When the user toggles `useBrand` on,
  // we pre-fill the 4 product fields + product image from this profile (and lock
  // them with a visual cue). Toggling off restores manual entry.
  //
  // For brands with multiple products (t-shirt brand etc.), the brand profile
  // also exposes a `products` catalog. When useBrand is on and there are 2+
  // products, the picker below lets the user choose which one to advertise.
  // The picked product's image becomes the Nano Banana / Sora reference.
  interface BrandProfile {
    productName: string
    description: string
    keyBenefits: string
    defaultCta: string
    productImageUrl?: string
  }
  interface BrandProduct { id: string; name: string; image_url: string | null }
  const [brand, setBrand] = useState<BrandProfile | null>(null)
  const [products, setProducts] = useState<BrandProduct[]>([])
  const [selectedProductId, setSelectedProductId] = useState<string | null>(null)
  const [useBrand, setUseBrand] = useState(false)

  // Two-step flow: form → script review → video
  const [step, setStep] = useState<'form' | 'script'>('form')
  const [generatedScript, setGeneratedScript] = useState<string>('')
  const [scriptLoading, setScriptLoading] = useState(false)
  const [editedScript, setEditedScript] = useState<string>('')
  const [scriptError, setScriptError] = useState<string | null>(null)

  // Hook-preview stage
  const [hooks, setHooks] = useState<HookVariant[] | null>(null)
  const [hooksLoading, setHooksLoading] = useState(false)
  const [hooksError, setHooksError] = useState<string | null>(null)

  // Fetch a saved brand image URL, convert to base64, and shove it into the
  // productImage state so the existing orchestrate pipeline reads it like a
  // freshly-uploaded file. Used when the brand toggle flips ON.
  async function loadBrandImage(url: string) {
    try {
      const res = await fetch(url)
      if (!res.ok) return null
      const blob = await res.blob()
      const buf = await blob.arrayBuffer()
      const bytes = new Uint8Array(buf)
      let bin = ''
      for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i])
      const base64 = btoa(bin)
      const mimeType = blob.type || 'image/png'
      return {
        base64,
        mimeType,
        preview: `data:${mimeType};base64,${base64}`,
      }
    } catch {
      return null
    }
  }

  // Load the user's brand profile + product catalog once. If they have a
  // meaningful brand (name present), default useBrand to ON. If multiple
  // products exist, default to the first one.
  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const supabase = getSupabase()
        if (!supabase) return
        const { data: sess } = await supabase.auth.getSession()
        const token = sess?.session?.access_token
        if (!token) return

        const [brandRes, productsRes] = await Promise.all([
          fetch('/api/brand/load', { headers: { Authorization: `Bearer ${token}` } }),
          fetch('/api/brand/products', { headers: { Authorization: `Bearer ${token}` } }),
        ])
        const brandData = await brandRes.json()
        const productsData = await productsRes.json()
        if (cancelled) return

        const list: BrandProduct[] = Array.isArray(productsData?.products) ? productsData.products : []
        setProducts(list)

        const p = brandData?.profile
        if (!p?.company_name) return

        const profile: BrandProfile = {
          productName: p.company_name ?? '',
          description: p.description ?? '',
          keyBenefits: p.unique_value_prop ?? '',
          defaultCta: p.brand_mission ?? 'Try it today',
          productImageUrl: p.logo_url ?? undefined,
        }
        setBrand(profile)
        setUseBrand(true)
        // Brand text fields. Note: productName here is actually the BRAND name
        // (we share the same column). When a specific product is picked below
        // we override productName with that product's name.
        setProductDescription(profile.description)
        setBenefits(profile.keyBenefits)
        setCallToAction(profile.defaultCta)

        // Pick the first catalog product as the default. Its image becomes the
        // first-frame seed; its name overrides the brand name in the form.
        const first = list[0]
        if (first) {
          setSelectedProductId(first.id)
          setProductName(first.name)
          if (first.image_url) {
            loadBrandImage(first.image_url).then(img => {
              if (!cancelled && img) setProductImage(img)
            })
          }
        } else {
          // No catalog yet — fall back to the legacy single image + brand name.
          setProductName(profile.productName)
          if (profile.productImageUrl) {
            loadBrandImage(profile.productImageUrl).then(img => {
              if (!cancelled && img) setProductImage(img)
            })
          }
        }
      } catch {
        // brand load is non-critical — silent failure is fine
      }
    })()
    return () => { cancelled = true }
  }, [])

  // Pick a product from the catalog — swaps the product name + first-frame image.
  async function pickProduct(id: string) {
    const p = products.find(x => x.id === id)
    if (!p) return
    setSelectedProductId(id)
    setProductName(p.name)
    if (p.image_url) {
      const img = await loadBrandImage(p.image_url)
      if (img) setProductImage(img)
    }
  }

  // When the user flips the toggle, sync the form fields accordingly.
  async function toggleUseBrand(next: boolean) {
    setUseBrand(next)
    if (next && brand) {
      setProductName(brand.productName)
      setProductDescription(brand.description)
      setBenefits(brand.keyBenefits)
      setCallToAction(brand.defaultCta)
      if (brand.productImageUrl) {
        const img = await loadBrandImage(brand.productImageUrl)
        if (img) setProductImage(img)
      }
    } else if (!next) {
      setProductName('')
      setProductDescription('')
      setBenefits('')
      setCallToAction('Try it today')
      setProductImage(null)
    }
  }

  // UGC always renders the full pipeline. Single tier now (Kling v3 omni handles voice natively).
  const includesVideo = true
  const videoCredits = calculateVideoCredits(tier, duration)
  const totalCredits = videoCredits
  const canGenerate = !scriptLoading && productName.trim() && productDescription.trim() && benefits.trim()

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = () => {
      const dataUrl = reader.result as string
      const [header, base64] = dataUrl.split(',')
      const mimeType = header.match(/data:(.*);base64/)?.[1] ?? 'image/jpeg'
      setProductImage({ base64, mimeType, preview: dataUrl })
    }
    reader.readAsDataURL(file)
  }

  const resetForm = () => {
    setProductName('')
    setProductDescription('')
    setBenefits('')
  }

  const runGenerate = async (selectedHook?: string, prewrittenScript?: string) => {
    await onGenerate({
      ugcType: UGC_TYPE, tier, duration, productName, productDescription, benefits, callToAction,
      style: 'realistic', imageSize: '1024x1024', voiceId: '',
      productImageBase64: productImage?.base64,
      productImageMimeType: productImage?.mimeType,
      selectedHook,
      character,
      customInstructions: customInstructions.trim() || undefined,
      language,
      aspect,
      actorId,
      customPhotoBase64: customPhoto?.base64,
      customPhotoMimeType: customPhoto?.mimeType,
      productType,
      prewrittenScript,
    })
    // Reset to form step after successful generation
    setStep('form')
    setGeneratedScript('')
    setEditedScript('')
    resetForm()
  }

  async function fetchShopifyProducts() {
    if (!shopifyUrl.trim()) return
    setShopifyLoading(true)
    setShopifyError(null)
    setShopifyProducts(null)
    setSelectedShopifyProduct(null)
    try {
      const res = await fetch(`/api/shopify/products?store=${encodeURIComponent(shopifyUrl.trim())}`)
      const data = await res.json()
      if (data.error) throw new Error(data.error)
      setShopifyProducts(data.products)
    } catch (e) {
      setShopifyError(e instanceof Error ? e.message : 'Failed to fetch products')
    } finally {
      setShopifyLoading(false)
    }
  }

  function applyShopifyProduct(product: ShopifyProduct) {
    setSelectedShopifyProduct(product)
    setProductName(product.title)
    // Strip HTML tags from body_html for description
    const desc = product.body_html.replace(/<[^>]+>/g, '').trim().slice(0, 400)
    setProductDescription(desc)
    // Load first image as product image
    if (product.images[0]) {
      fetch(product.images[0])
        .then(r => r.blob())
        .then(blob => {
          const reader = new FileReader()
          reader.onload = () => {
            const dataUrl = reader.result as string
            const [meta, base64] = dataUrl.split(',')
            const mimeType = meta.match(/:(.*?);/)?.[1] ?? 'image/jpeg'
            setProductImage({ base64, mimeType, preview: product.images[0] })
          }
          reader.readAsDataURL(blob)
        })
        .catch(() => {/* image load failed, skip */})
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!canGenerate || isLoading || scriptLoading) return

    setScriptError(null)
    setScriptLoading(true)
    try {
      const supabase = getSupabase()
      if (!supabase) throw new Error('Auth not ready')
      const { data: sessionData } = await supabase.auth.getSession()
      const token = sessionData?.session?.access_token
      if (!token) throw new Error('Not signed in')

      const res = await fetch('/api/ugc/script', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({
          productName, productDescription, benefits,
          callToAction: callToAction || 'Try it today',
          productImageBase64: productImage?.base64,
          productImageMimeType: productImage?.mimeType,
          duration,
          character,
          customInstructions: customInstructions.trim() || undefined,
          language,
          productType,
        }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Failed to generate script')
      if (!data.script) throw new Error('No script returned')
      setGeneratedScript(data.script)
      setEditedScript(data.script)
      setStep('script')
    } catch (err) {
      setScriptError(err instanceof Error ? err.message : 'Failed to generate script')
    } finally {
      setScriptLoading(false)
    }
  }

  const handleHookPick = async (hook: HookVariant) => {
    setHooks(null)
    await runGenerate(hook.text)
  }

  const handleSkipHook = async () => {
    setHooks(null)
    await runGenerate()
  }

  // Script review step — shown after "Generate Script" succeeds
  if (step === 'script') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
        <section className="card" style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <button
              type="button"
              onClick={() => setStep('form')}
              disabled={isLoading}
              style={{
                display: 'flex', alignItems: 'center', gap: 6,
                padding: '6px 12px', borderRadius: 8,
                border: '1px solid var(--border)', background: 'var(--surface)',
                color: 'var(--ink-dim)', fontSize: 13, cursor: isLoading ? 'not-allowed' : 'pointer',
                transition: 'all 0.15s',
              }}
            >
              ← Edit form
            </button>
            <h3 style={{ margin: 0, fontSize: 16, fontWeight: 600, color: 'var(--ink)' }}>
              Review your script
            </h3>
          </div>

          <p style={{ margin: 0, fontSize: 12.5, color: 'var(--ink-dim)', lineHeight: 1.5 }}>
            You can edit the script before generating. Changes here affect what the character says.
          </p>

          <textarea
            value={editedScript}
            onChange={e => setEditedScript(e.target.value)}
            disabled={isLoading}
            rows={16}
            style={{
              width: '100%',
              fontFamily: 'var(--font-mono)',
              fontSize: 12.5,
              lineHeight: 1.65,
              padding: '14px',
              borderRadius: 10,
              border: '1.5px solid var(--border-strong)',
              background: 'var(--bg-elev)',
              color: 'var(--ink)',
              resize: 'vertical',
              boxSizing: 'border-box',
              outline: 'none',
            }}
          />
        </section>

        <section className="card" style={{ display: 'flex', flexDirection: 'column', gap: 11 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', padding: '6px 0', borderBottom: '1px solid var(--border-soft)' }}>
            <span style={{ fontSize: 13, color: 'var(--ink-dim)' }}>Cost</span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 22, fontWeight: 500, letterSpacing: '-0.03em' }}>
              {totalCredits} <span style={{ fontSize: 12, color: 'var(--ink-mute)' }}>cr</span>
            </span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12.5, color: 'var(--ink-mute)' }}>
            <span>Your balance</span>
            <span style={{ color: creditBalance >= totalCredits ? 'var(--good)' : 'var(--danger)', fontWeight: 600 }}>
              {creditBalance} credits
            </span>
          </div>

          <button
            type="button"
            disabled={isLoading || !editedScript.trim() || creditBalance < totalCredits}
            onClick={() => runGenerate(undefined, editedScript)}
            className="btn btn-primary"
            style={{ padding: '13px', fontSize: '14px', marginTop: '4px', borderRadius: 11 }}
          >
            {isLoading ? 'Generating…' : 'Generate Video →'}
          </button>

          {creditBalance < totalCredits && (
            <p style={{ fontSize: 11.5, color: 'var(--ink-mute)', textAlign: 'center', margin: 0 }}>
              Not enough credits — need {totalCredits}, have {creditBalance}
            </p>
          )}
        </section>
      </div>
    )
  }

  return (
    <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>

      {/* 1 — Format (tier + duration) */}
      <section className="card">
        <div className="section-step-head">
          <span className="step-circle">1</span>
          <h3>Format</h3>
        </div>

          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 9 }}>
            <span style={{ fontSize: 12.5, fontWeight: 600, color: 'var(--ink-2)' }}>Duration</span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--ink-fade)' }}>
              ~{Math.round(estimateRenderSeconds(duration) / 60)}m render
            </span>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: `repeat(${DURATION_OPTIONS.length}, 1fr)`, gap: 8 }}>
            {DURATION_OPTIONS.map(sec => {
              const dCfg = DURATION_CONFIGS[sec]
              const active = duration === sec
              const cost = calculateVideoCredits(tier, sec)
              const usd = creditsToUSD(cost)
              const locked = !dCfg.available
              const chained = dCfg.klingClips >= 2
              return (
                <button
                  key={sec}
                  type="button"
                  onClick={() => !locked && setDuration(sec)}
                  disabled={isLoading || locked}
                  title={chained ? 'Chained from 2 Kling clips' : undefined}
                  style={{
                    textAlign: 'center',
                    cursor: locked ? 'not-allowed' : (isLoading ? 'not-allowed' : 'pointer'),
                    padding: '10px 6px', borderRadius: 10,
                    border: `1px solid ${active ? 'var(--ink)' : 'var(--border)'}`,
                    background: active ? 'var(--ink)' : 'var(--surface)',
                    color: active ? '#fff' : 'var(--ink)',
                    opacity: locked ? 0.45 : 1,
                    transition: 'all 0.15s',
                    display: 'flex', flexDirection: 'column', gap: 2,
                  }}>
                  <span style={{ fontSize: 14.5, fontWeight: 600 }}>{sec}s</span>
                  <span style={{ fontSize: 10.5, opacity: 0.75, fontFamily: 'var(--font-mono)' }}>{cost} cr · ${usd.toFixed(2)}</span>
                </button>
              )
            })}
          </div>

          <div style={{ marginTop: 18 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 9 }}>
              <span style={{ fontSize: 12.5, fontWeight: 600, color: 'var(--ink-2)' }}>Aspect</span>
              <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--ink-fade)' }}>
                {ASPECTS[aspect].soraSize}
              </span>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>
              {(Object.keys(ASPECTS) as UGCAspect[]).map(a => {
                const cfg = ASPECTS[a]
                const active = aspect === a
                // Visual cue: a small box mirroring the aspect inside each button.
                const boxW = a === 'portrait' ? 14 : a === 'square' ? 18 : 22
                const boxH = a === 'portrait' ? 22 : a === 'square' ? 18 : 12
                return (
                  <button
                    key={a}
                    type="button"
                    onClick={() => setAspect(a)}
                    disabled={isLoading}
                    style={{
                      textAlign: 'left',
                      padding: '10px 12px', borderRadius: 11,
                      border: `1.5px solid ${active ? 'var(--ink)' : 'var(--border)'}`,
                      background: active ? 'var(--hover)' : 'var(--surface)',
                      cursor: isLoading ? 'not-allowed' : 'pointer',
                      transition: 'all 0.15s',
                      display: 'flex', alignItems: 'center', gap: 10,
                    }}>
                    <span style={{
                      width: boxW, height: boxH, flexShrink: 0,
                      borderRadius: 3,
                      background: active ? 'var(--ink)' : 'var(--ink-faint)',
                    }} />
                    <span style={{ display: 'flex', flexDirection: 'column', minWidth: 0 }}>
                      <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--ink)', letterSpacing: '-0.01em' }}>{cfg.label}</span>
                      <span style={{ fontSize: 10.5, color: 'var(--ink-mute)', fontFamily: 'var(--font-mono)' }}>{cfg.hint}</span>
                    </span>
                  </button>
                )
              })}
            </div>
          </div>
      </section>

      {/* 2 — Your product */}
      <section className="card" style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
        <div className="section-step-head" style={{ marginBottom: 0 }}>
          <span className="step-circle">2</span>
          <h3>Your product</h3>
        </div>

        {/* Shopify Product Picker */}
        <div style={{ padding: '14px 16px', borderRadius: 10, border: '1px solid var(--border)', background: 'var(--surface-2)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 0 1-8 0"/></svg>
            <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--ink)' }}>Import from Shopify</span>
            <span style={{ fontSize: 11, color: 'var(--ink-mute)', marginLeft: 'auto' }}>optional</span>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <input
              type="text"
              placeholder="yourstore.myshopify.com"
              value={shopifyUrl}
              onChange={e => setShopifyUrl(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && fetchShopifyProducts()}
              style={{ flex: 1, padding: '8px 12px', borderRadius: 8, border: '1px solid var(--border)', background: 'var(--surface)', color: 'var(--ink)', fontSize: 13, outline: 'none' }}
            />
            <button
              type="button"
              onClick={fetchShopifyProducts}
              disabled={!shopifyUrl.trim() || shopifyLoading}
              style={{ padding: '8px 14px', borderRadius: 8, border: 'none', background: 'var(--ink)', color: 'var(--surface)', fontSize: 13, fontWeight: 600, cursor: shopifyUrl.trim() && !shopifyLoading ? 'pointer' : 'not-allowed', opacity: shopifyUrl.trim() && !shopifyLoading ? 1 : 0.4, whiteSpace: 'nowrap' as const, display: 'flex', alignItems: 'center', gap: 6 }}
            >
              {shopifyLoading ? <><span style={{ width: 12, height: 12, borderRadius: '50%', border: '2px solid rgba(255,255,255,0.3)', borderTopColor: '#fff', display: 'inline-block', animation: 'spin 0.7s linear infinite' }} />Loading...</> : 'Fetch Products'}
            </button>
          </div>
          {shopifyError && (
            <div style={{ marginTop: 8, fontSize: 12, color: '#e84040', padding: '6px 10px', borderRadius: 6, background: 'rgba(232,64,64,0.08)', border: '1px solid rgba(232,64,64,0.2)' }}>
              {shopifyError}. Make sure the URL is correct (e.g. yourstore.myshopify.com).
            </div>
          )}
          {shopifyProducts && shopifyProducts.length === 0 && (
            <div style={{ marginTop: 8, fontSize: 12, color: 'var(--ink-mute)' }}>No products found in this store.</div>
          )}
          {shopifyProducts && shopifyProducts.length > 0 && (
            <div style={{ marginTop: 12 }}>
              <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase' as const, color: 'var(--ink-mute)', marginBottom: 8 }}>{shopifyProducts.length} products — pick one to advertise</div>
              <div style={{ display: 'flex', flexDirection: 'column' as const, gap: 6, maxHeight: 260, overflowY: 'auto' as const }}>
                {shopifyProducts.map(product => {
                  const isSelected = selectedShopifyProduct?.id === product.id
                  return (
                    <div key={product.id} onClick={() => applyShopifyProduct(product)} style={{ display: 'flex', gap: 10, alignItems: 'center', padding: '8px 10px', borderRadius: 8, cursor: 'pointer', border: `1px solid ${isSelected ? 'var(--ink)' : 'var(--border)'}`, background: isSelected ? 'var(--accent-soft)' : 'var(--surface)', transition: 'all 0.15s' }}>
                      {product.images[0]
                        ? <img src={product.images[0]} alt="" style={{ width: 40, height: 40, objectFit: 'cover', borderRadius: 6, flexShrink: 0 }} />
                        : <div style={{ width: 40, height: 40, borderRadius: 6, background: 'var(--surface-2)', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18 }}>📦</div>
                      }
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--ink)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const }}>{product.title}</div>
                        <div style={{ fontSize: 11, color: 'var(--ink-mute)' }}>${product.price}</div>
                      </div>
                      {isSelected && <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M20 6L9 17l-5-5" strokeLinecap="round" strokeLinejoin="round"/></svg>}
                    </div>
                  )
                })}
              </div>
              {selectedShopifyProduct && <div style={{ marginTop: 8, fontSize: 12, color: 'var(--ink-mute)' }}>✓ {selectedShopifyProduct.title} selected — fields below pre-filled</div>}
            </div>
          )}
        </div>

        {/* Brand profile toggle — only render when a brand profile actually exists.
            On = pre-fills the 4 fields from /settings/brand. Off = manual entry. */}
        {brand && (
          <label style={{
            display: 'flex', alignItems: 'center', gap: 12,
            padding: '12px 14px', borderRadius: 11,
            background: useBrand ? 'var(--ink)' : 'var(--surface-2)',
            border: `1px solid ${useBrand ? 'var(--ink)' : 'var(--border)'}`,
            color: useBrand ? '#fff' : 'var(--ink)',
            cursor: 'pointer', transition: 'all 0.15s',
          }}>
            <span style={{
              position: 'relative', flexShrink: 0,
              width: 32, height: 18, borderRadius: 99,
              background: useBrand ? 'rgba(255,255,255,0.25)' : 'var(--border-strong)',
              transition: 'background 0.15s',
            }}>
              <span style={{
                position: 'absolute', top: 2, left: useBrand ? 16 : 2,
                width: 14, height: 14, borderRadius: '50%',
                background: '#fff', transition: 'left 0.15s',
              }} />
            </span>
            <input type="checkbox" checked={useBrand} onChange={e => toggleUseBrand(e.target.checked)}
              disabled={isLoading}
              style={{ position: 'absolute', opacity: 0, pointerEvents: 'none' }} />
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 13, fontWeight: 600, letterSpacing: '-0.01em' }}>
                Use my brand profile
              </div>
              <div style={{
                fontSize: 11.5,
                color: useBrand ? 'rgba(255,255,255,0.7)' : 'var(--ink-mute)',
                marginTop: 2,
              }}>
                {useBrand ? `Pre-filled with “${brand.productName}”` : 'Or fill the fields manually below'}
              </div>
            </div>
          </label>
        )}

        {/* Product picker — shown when the catalog has 2+ products. Lets a
            t-shirt brand (etc.) pick which SKU this UGC is for. */}
        {useBrand && products.length > 1 && (
          <div>
            <span style={{ display: 'block', fontSize: 12.5, fontWeight: 600, color: 'var(--ink-2)', marginBottom: 8 }}>
              Which product?
            </span>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 8 }}>
              {products.map(p => {
                const active = selectedProductId === p.id
                return (
                  <button
                    key={p.id}
                    type="button"
                    onClick={() => pickProduct(p.id)}
                    disabled={isLoading}
                    style={{
                      display: 'flex', flexDirection: 'column', gap: 6,
                      padding: 8, borderRadius: 11,
                      background: active ? 'var(--hover)' : 'var(--surface)',
                      border: `1.5px solid ${active ? 'var(--ink)' : 'var(--border)'}`,
                      cursor: isLoading ? 'not-allowed' : 'pointer',
                      transition: 'all 0.15s', textAlign: 'left',
                    }}>
                    <div style={{ aspectRatio: '1', borderRadius: 7, overflow: 'hidden', background: 'var(--bg-elev)' }}>
                      {p.image_url && (
                        <img src={p.image_url} alt={p.name}
                          style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
                      )}
                    </div>
                    <span style={{
                      fontSize: 12, fontWeight: 600, color: 'var(--ink)',
                      letterSpacing: '-0.01em', lineHeight: 1.3,
                      overflow: 'hidden', textOverflow: 'ellipsis',
                      display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' as const,
                    }}>{p.name}</span>
                  </button>
                )
              })}
            </div>
          </div>
        )}

        {/* Product type toggle */}
        <div className="form-row">
          <label className="form-label">Product type</label>
          <div style={{ display: 'flex', gap: 8, marginBottom: 4 }}>
            {(['physical', 'software'] as const).map(type => (
              <button
                key={type}
                type="button"
                onClick={() => setProductType(type)}
                disabled={isLoading}
                style={{
                  padding: '7px 16px',
                  borderRadius: 8,
                  border: `1.5px solid ${productType === type ? 'var(--ink)' : 'var(--border)'}`,
                  background: productType === type ? 'var(--ink)' : 'transparent',
                  color: productType === type ? '#fff' : 'var(--ink-mute)',
                  fontSize: 13,
                  fontWeight: 600,
                  cursor: isLoading ? 'not-allowed' : 'pointer',
                }}
              >
                {type === 'physical' ? 'Physical product' : 'Software / App'}
              </button>
            ))}
          </div>
        </div>

        <div className="form-row">
          <label className="form-label">Product name</label>
          <input className="input" value={productName} onChange={e => { setProductName(e.target.value); if (useBrand) setUseBrand(false) }}
            placeholder="e.g. ContentFlow" disabled={isLoading} />
        </div>

        <div className="form-row">
          <label className="form-label">One-line description</label>
          <textarea className="textarea" rows={3} value={productDescription}
            onChange={e => { setProductDescription(e.target.value); if (useBrand) setUseBrand(false) }}
            placeholder="What it is and who it's for, in a sentence." disabled={isLoading} />
        </div>

        <div className="form-row">
          <label className="form-label">Key benefits</label>
          <textarea className="textarea" rows={3} value={benefits}
            onChange={e => { setBenefits(e.target.value); if (useBrand) setUseBrand(false) }}
            placeholder="Save time · ships to all platforms · AI-powered" disabled={isLoading} />
        </div>

        <div className="form-row">
          <label className="form-label">Call to action</label>
          <input className="input" value={callToAction} onChange={e => { setCallToAction(e.target.value); if (useBrand) setUseBrand(false) }}
            placeholder="e.g. Try it free today" disabled={isLoading} />
        </div>


        <div className="form-row">
          <label className="form-label">
            {productType === 'software' ? 'App screenshot' : 'Product photo'}{' '}
            <span style={{ color: 'var(--ink-mute)', fontWeight: 400 }}>(required)</span>
          </label>
          <p className="help">
            {productType === 'software'
              ? 'This will appear as the background behind the character.'
              : 'Nano Banana composites your real product into the Sora 2 first frame.'}
          </p>
          <label style={{
            display: 'flex', alignItems: 'center', gap: '14px',
            padding: '12px 14px', borderRadius: 12,
            border: '1.5px dashed var(--border-strong)', cursor: isLoading ? 'default' : 'pointer',
            background: 'var(--bg-elev)',
            transition: 'border-color 0.15s',
          }}>
            <input type="file" accept="image/jpeg,image/png,image/webp"
              onChange={handleImageChange} disabled={isLoading}
              style={{ display: 'none' }} />
            {productImage ? (
              <>
                <img src={productImage.preview} alt="Product"
                  style={{ width: 48, height: 48, objectFit: 'cover', borderRadius: 8, flexShrink: 0 }} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <p style={{ fontSize: '13px', fontWeight: 600, color: 'var(--ink)', margin: 0 }}>Photo added</p>
                  <p style={{ fontSize: '12px', color: 'var(--ink-mute)', margin: '2px 0 0' }}>Click to change</p>
                </div>
                <button type="button" onClick={e => { e.preventDefault(); setProductImage(null) }}
                  disabled={isLoading}
                  style={{ fontSize: '18px', lineHeight: 1, background: 'none', border: 'none', color: 'var(--ink-mute)', cursor: 'pointer', padding: '0 4px' }}>
                  ×
                </button>
              </>
            ) : (
              <>
                <div style={{ width: 48, height: 48, borderRadius: 8, background: 'var(--surface)', border: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--ink-mute)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M12 16V4M7 9l5-5 5 5"/><path d="M4 16v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-3"/></svg>
                </div>
                <div>
                  <p style={{ fontSize: '13px', fontWeight: 600, color: 'var(--ink)', margin: 0 }}>{productType === 'software' ? 'Drop app screenshot' : 'Drop product photo'}</p>
                  <p style={{ fontSize: '11px', color: 'var(--ink-mute)', margin: '2px 0 0', fontFamily: 'var(--font-mono)', letterSpacing: '0.04em' }}>PNG · JPG · WEBP</p>
                </div>
              </>
            )}
          </label>
        </div>
      </section>

      {/* 3 — Character + voice */}
      <section className="card" style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
        <div className="section-step-head" style={{ marginBottom: 0 }}>
          <span className="step-circle">3</span>
          <h3>Character &amp; setting</h3>
        </div>

          <p style={{ fontSize: 12.5, color: 'var(--ink-dim)', margin: 0, lineHeight: 1.5 }}>
            Pick a pre-built actor from the library or build a custom character — Kling v3 will generate them holding your real product and speaking your script with a synced native voice.
          </p>

          <ActorPicker
            value={character}
            onChange={(profile, id, photo) => {
              setCharacter(profile)
              setActorId(id)
              setCustomPhoto(photo)
            }}
            disabled={isLoading}
          />
      </section>

      {/* 4 — Customize */}
      <section className="card" style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
        <div className="section-step-head" style={{ marginBottom: 0 }}>
          <span className="step-circle">4</span>
          <h3>Customize</h3>
        </div>

        <div className="form-row">
          <label className="form-label">Language</label>
          <p className="help">Script, hooks, voice and captions render in this language. Sora&apos;s lip-sync follows the spoken language.</p>
          <select className="select" value={language} onChange={e => setLanguage(e.target.value)} disabled={isLoading}>
            {LANGUAGES.map(lang => (
              <option key={lang.code} value={lang.code}>
                {lang.nativeLabel} {lang.code !== 'en' ? `— ${lang.name}` : ''}
              </option>
            ))}
          </select>
        </div>

        <div className="form-row">
          <label className="form-label">Custom instructions <span style={{ color: 'var(--ink-mute)', fontWeight: 400 }}>(optional)</span></label>
          <p className="help">Paste your own script, set a tone, mention an offer, target an audience. The AI obeys.</p>
          <textarea
            className="textarea"
            value={customInstructions}
            onChange={e => setCustomInstructions(e.target.value.slice(0, 1500))}
            disabled={isLoading}
            rows={4}
            placeholder={'• Use this script: "Three drops, every morning."\n• Make it sound like a college student\n• Mention the 30% launch discount'}
            style={{ minHeight: 84 }}
          />
          <p style={{ fontSize: 10.5, color: 'var(--ink-fade)', textAlign: 'right', margin: '4px 0 0', fontFamily: 'var(--font-mono)' }}>
            {customInstructions.length} / 1500
          </p>
        </div>
      </section>

      {/* 6 — Cost summary + generate */}
      <section className="card" style={{ display: 'flex', flexDirection: 'column', gap: 11 }}>
        <div className="section-step-head" style={{ marginBottom: 0 }}>
          <span className="step-circle">5</span>
          <h3>Ready when you are</h3>
        </div>

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', padding: '6px 0', borderBottom: '1px solid var(--border-soft)' }}>
          <span style={{ fontSize: 13, color: 'var(--ink-dim)' }}>Cost</span>
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: 22, fontWeight: 500, letterSpacing: '-0.03em' }}>{totalCredits} <span style={{ fontSize: 12, color: 'var(--ink-mute)' }}>cr</span></span>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12.5, color: 'var(--ink-mute)' }}>
          <span>Your balance</span>
          <span style={{ color: creditBalance >= totalCredits ? 'var(--good)' : 'var(--danger)', fontWeight: 600 }}>
            {creditBalance} credits
          </span>
        </div>

        <button type="submit" disabled={!canGenerate || isLoading || scriptLoading} className="btn btn-primary"
          style={{ padding: '13px', fontSize: '14px', marginTop: '4px', borderRadius: 11 }}>
          {scriptLoading ? 'Writing script…' : 'Generate Script →'}
        </button>

        {scriptError && (
          <p style={{ fontSize: 12, color: 'var(--danger)', textAlign: 'center', margin: 0 }}>{scriptError}</p>
        )}

        {(!canGenerate || creditBalance < totalCredits) && productName && (
          <p style={{ fontSize: 11.5, color: 'var(--ink-mute)', textAlign: 'center', margin: 0 }}>
            {creditBalance < totalCredits
              ? `Not enough credits — need ${totalCredits}, have ${creditBalance}`
              : 'Fill in all required fields'}
          </p>
        )}
      </section>

      {hooks && (
        <div
          role="dialog"
          aria-modal="true"
          style={{
            position: 'fixed', inset: 0, zIndex: 100,
            background: 'rgba(0,0,0,0.55)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            padding: '20px',
          }}
          onClick={() => !isLoading && setHooks(null)}
        >
          <div
            onClick={e => e.stopPropagation()}
            style={{
              background: 'var(--surface)', border: '1px solid var(--border)',
              borderRadius: 'var(--r-lg)', padding: '24px',
              maxWidth: '560px', width: '100%',
              display: 'flex', flexDirection: 'column', gap: '16px',
              maxHeight: '90vh', overflowY: 'auto',
            }}
          >
            <div>
              <h3 style={{ margin: 0, fontSize: '18px', color: 'var(--ink)' }}>Pick your hook</h3>
              <p style={{ margin: '4px 0 0', fontSize: '13px', color: 'var(--ink-dim)' }}>
                Different angles for the first 5 seconds. Picking one charges {totalCredits} credits.
              </p>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {hooks.map(h => (
                <button
                  key={h.id}
                  type="button"
                  onClick={() => handleHookPick(h)}
                  disabled={isLoading}
                  style={{
                    textAlign: 'left', cursor: isLoading ? 'not-allowed' : 'pointer',
                    padding: '14px 16px', borderRadius: 'var(--r-md)',
                    border: '1px solid var(--border)', background: 'var(--surface)',
                    transition: 'all 0.15s',
                    display: 'flex', flexDirection: 'column', gap: '6px',
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                    <span style={{
                      fontSize: 10.5, fontWeight: 600, letterSpacing: '0.03em', textTransform: 'uppercase',
                      color: 'var(--ink-2)', background: 'var(--hover)',
                      borderRadius: 5, padding: '2px 8px',
                    }}>
                      {h.angle}
                    </span>
                    <span style={{ fontSize: 11, color: 'var(--ink-mute)', fontStyle: 'italic' }}>{h.tone}</span>
                  </div>
                  <p style={{ margin: 0, fontSize: 14.5, color: 'var(--ink)', lineHeight: 1.5, fontFamily: 'var(--font-serif)', fontStyle: 'italic' }}>
                    “{h.text}”
                  </p>
                </button>
              ))}
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', gap: '8px', marginTop: '4px' }}>
              <button type="button" onClick={() => setHooks(null)} disabled={isLoading}
                className="btn btn-ghost" style={{ fontSize: '13px' }}>
                Cancel
              </button>
              <button type="button" onClick={handleSkipHook} disabled={isLoading}
                className="btn btn-ghost" style={{ fontSize: '13px' }}>
                Use original hook
              </button>
            </div>
          </div>
        </div>
      )}
    </form>
  )
}
