import type { CharacterProfile } from './character'

// Curated library of UGC actors. Users pick one and the full CharacterProfile
// is dropped into the orchestrate call — same downstream path as the custom
// CharacterBuilder, just with pre-defined values.
//
// `portrait` is a path under /public/actors/. Portraits are generated once by
// scripts/generate-actor-portraits.ts and committed to the repo so the picker
// loads instantly with zero API cost.

export interface Actor {
  id: string
  name: string
  tagline: string         // 3-5 word vibe descriptor for the card
  portrait: string        // /actors/<id>.jpg
  profile: CharacterProfile
}

export const ACTORS: Actor[] = [
  {
    id: 'maya',
    name: 'Maya',
    tagline: 'Skincare & beauty',
    portrait: '/actors/maya.jpg',
    profile: {
      gender: 'Woman',
      age: 'Early 20s',
      ethnicity: 'Northern European',
      hair: 'Brown straight-wavy',
      uniqueFeatures: 'Freckles',
      scene: 'Well-decorated bedroom',
      mood: 'Engaged',
      outfit: 'White tank top',
      accessories: 'Necklace',
    },
  },
  {
    id: 'liam',
    name: 'Liam',
    tagline: 'Tech & lifestyle',
    portrait: '/actors/liam.jpg',
    profile: {
      gender: 'Man',
      age: 'Late 20s',
      ethnicity: 'Northern European',
      hair: 'Dark brown wavy',
      uniqueFeatures: 'Beard',
      scene: 'Living room',
      mood: 'Confident',
      outfit: 'Casual t-shirt',
      accessories: 'Glasses',
    },
  },
  {
    id: 'amara',
    name: 'Amara',
    tagline: 'Wellness & yoga',
    portrait: '/actors/amara.jpg',
    profile: {
      gender: 'Woman',
      age: 'Early 30s',
      ethnicity: 'West African',
      hair: 'Black coily / afro',
      uniqueFeatures: 'None',
      scene: 'Yoga studio',
      mood: 'Chill',
      outfit: 'Yoga set',
      accessories: 'None',
    },
  },
  {
    id: 'diego',
    name: 'Diego',
    tagline: 'Fitness & gym',
    portrait: '/actors/diego.jpg',
    profile: {
      gender: 'Man',
      age: 'Late 20s',
      ethnicity: 'Latin American',
      hair: 'Black straight',
      uniqueFeatures: 'Tattoo visible',
      scene: 'Gym',
      mood: 'Energetic',
      outfit: 'Athletic wear',
      accessories: 'None',
    },
  },
  {
    id: 'noah',
    name: 'Noah',
    tagline: 'Street & streetwear',
    portrait: '/actors/noah.jpg',
    profile: {
      gender: 'Man',
      age: 'Early 20s',
      ethnicity: 'Mixed',
      hair: 'Dark brown curly',
      uniqueFeatures: 'Piercing',
      scene: 'City street',
      mood: 'Confident',
      outfit: 'Streetwear',
      accessories: 'Cap',
    },
  },
  {
    id: 'leila',
    name: 'Leila',
    tagline: 'Café & lifestyle',
    portrait: '/actors/leila.jpg',
    profile: {
      gender: 'Woman',
      age: 'Late 20s',
      ethnicity: 'Middle Eastern',
      hair: 'Dark brown straight',
      uniqueFeatures: 'None',
      scene: 'Café',
      mood: 'Curious',
      outfit: 'Smart casual',
      accessories: 'Earrings',
    },
  },
  {
    id: 'marcus',
    name: 'Marcus',
    tagline: 'Dad-vibe & relatable',
    portrait: '/actors/marcus.jpg',
    profile: {
      gender: 'Man',
      age: '40s',
      ethnicity: 'Black / African American',
      hair: 'Black coily / afro',
      uniqueFeatures: 'Beard',
      scene: 'Living room',
      mood: 'Relaxed',
      outfit: 'Sweater',
      accessories: 'None',
    },
  },
  {
    id: 'sophie',
    name: 'Sophie',
    tagline: 'Skincare & everyday life',
    portrait: '/actors/sophie.jpg',
    profile: {
      gender: 'Woman',
      age: 'Early 20s',
      ethnicity: 'Northern European',
      hair: 'Light brown straight',
      uniqueFeatures: 'None',
      scene: 'Bathroom',
      mood: 'Candid',
      outfit: 'Oversized hoodie',
      accessories: 'Earrings',
    },
  },
  {
    id: 'jin',
    name: 'Jin',
    tagline: 'Minimal & polished',
    portrait: '/actors/jin.jpg',
    profile: {
      gender: 'Man',
      age: 'Early 30s',
      ethnicity: 'East Asian',
      hair: 'Black straight',
      uniqueFeatures: 'None',
      scene: 'Kitchen',
      mood: 'Candid',
      outfit: 'Button-up shirt',
      accessories: 'Watch',
    },
  },
  {
    id: 'isabela',
    name: 'Isabela',
    tagline: 'Tech & creator life',
    portrait: '/actors/isabela.jpg',
    profile: {
      gender: 'Woman',
      age: 'Late 20s',
      ethnicity: 'Northern European',
      hair: 'Blonde wavy',
      uniqueFeatures: 'Freckles',
      scene: 'Home office',
      mood: 'Excited',
      outfit: 'Oversized hoodie',
      accessories: 'Necklace',
    },
  },
  {
    id: 'priya',
    name: 'Priya',
    tagline: 'Tech & professional',
    portrait: '/actors/priya.jpg',
    profile: {
      gender: 'Woman',
      age: 'Late 20s',
      ethnicity: 'South Asian',
      hair: 'Black long straight',
      uniqueFeatures: 'None',
      scene: 'Home office',
      mood: 'Confident',
      outfit: 'Silk camisole and cardigan',
      accessories: 'Small hoop earrings',
    },
  },
  {
    id: 'kai',
    name: 'Kai',
    tagline: 'Outdoor & lifestyle',
    portrait: '/actors/kai.jpg',
    profile: {
      gender: 'Man',
      age: 'Late 20s',
      ethnicity: 'Pacific Islander',
      hair: 'Black wavy medium',
      uniqueFeatures: 'Tan skin',
      scene: 'Kitchen',
      mood: 'Chill',
      outfit: 'Linen shirt',
      accessories: 'Cord necklace',
    },
  },
  {
    id: 'elena',
    name: 'Elena',
    tagline: 'Kitchen & home cook',
    portrait: '/actors/elena.jpg',
    profile: {
      gender: 'Woman',
      age: 'Early 30s',
      ethnicity: 'Mediterranean',
      hair: 'Dark brown curly',
      uniqueFeatures: 'None',
      scene: 'Kitchen',
      mood: 'Warm',
      outfit: 'Linen apron over t-shirt',
      accessories: 'None',
    },
  },
  {
    id: 'zara',
    name: 'Zara',
    tagline: 'Beauty & vanity',
    portrait: '/actors/zara.jpg',
    profile: {
      gender: 'Woman',
      age: 'Early 20s',
      ethnicity: 'East Asian',
      hair: 'Black straight with bangs',
      uniqueFeatures: 'None',
      scene: 'Bathroom vanity',
      mood: 'Candid',
      outfit: 'Cropped tee',
      accessories: 'Small stud earrings',
    },
  },
  {
    id: 'jamal',
    name: 'Jamal',
    tagline: 'Fitness & wellness',
    portrait: '/actors/jamal.jpg',
    profile: {
      gender: 'Man',
      age: 'Early 30s',
      ethnicity: 'Black / African American',
      hair: 'Short fade',
      uniqueFeatures: 'Neat goatee',
      scene: 'Home gym',
      mood: 'Focused',
      outfit: 'Athletic tank',
      accessories: 'Fitness watch',
    },
  },
  {
    id: 'mia',
    name: 'Mia',
    tagline: 'Café & student life',
    portrait: '/actors/mia.jpg',
    profile: {
      gender: 'Woman',
      age: 'Early 20s',
      ethnicity: 'Southeast Asian',
      hair: 'Dark brown long straight',
      uniqueFeatures: 'None',
      scene: 'Café',
      mood: 'Curious',
      outfit: 'Cropped cardigan',
      accessories: 'Backpack strap visible',
    },
  },
  {
    id: 'naomi',
    name: 'Naomi',
    tagline: 'Professional & polished',
    portrait: '/actors/naomi.jpg',
    profile: {
      gender: 'Woman',
      age: 'Late 20s',
      ethnicity: 'Black / African American',
      hair: 'Natural coily medium-length',
      uniqueFeatures: 'Hoop earrings',
      scene: 'Home office',
      mood: 'Confident',
      outfit: 'Fitted turtleneck',
      accessories: 'Hoop earrings',
    },
  },
  {
    id: 'oliver',
    name: 'Oliver',
    tagline: 'Silver fox & kitchen',
    portrait: '/actors/oliver.jpg',
    profile: {
      gender: 'Man',
      age: '50s',
      ethnicity: 'Northern European',
      hair: 'Silver grey short',
      uniqueFeatures: 'Salt-and-pepper stubble',
      scene: 'Kitchen',
      mood: 'Relaxed',
      outfit: 'Rolled-sleeve button-up',
      accessories: 'Wristwatch',
    },
  },
  {
    id: 'hana',
    name: 'Hana',
    tagline: 'Wellness & morning routine',
    portrait: '/actors/hana.jpg',
    profile: {
      gender: 'Woman',
      age: 'Late 20s',
      ethnicity: 'East Asian',
      hair: 'Brown long straight',
      uniqueFeatures: 'None',
      scene: 'Kitchen with plants',
      mood: 'Serene',
      outfit: 'Loose linen top',
      accessories: 'Delicate necklace',
    },
  },
  {
    id: 'carlos',
    name: 'Carlos',
    tagline: 'Dad-vibe & living room',
    portrait: '/actors/carlos.jpg',
    profile: {
      gender: 'Man',
      age: '40s',
      ethnicity: 'Latin American',
      hair: 'Black short with grey at temples',
      uniqueFeatures: 'Short beard',
      scene: 'Living room',
      mood: 'Warm',
      outfit: 'Henley shirt',
      accessories: 'None',
    },
  },
]

export function getActor(id: string): Actor | undefined {
  return ACTORS.find(a => a.id === id)
}
