// UGC pipeline tier + duration + pricing config.
// Now Kling-v3-omni-only: single tier (no Hero/Standard split because voice
// is always generated by Kling natively — there's nothing to upgrade to).

export type UGCTier = 'standard'
export type ARollProvider = 'kling-v3-omni'

// Kling v3 omni-video supports 3-15s per generation. Longer videos chain
// clips that share the same Nano Banana start_image.
export type DurationStrategy = 'native' | 'chained'

export interface DurationConfig {
  totalSeconds: number              // total final video duration
  klingSeconds: 5 | 10 | 15         // length of each Kling generation
  klingClips: 1 | 2                 // how many Kling generations to chain
  strategy: DurationStrategy
  label: string
  available: boolean
}

export const DURATION_CONFIGS: Record<number, DurationConfig> = {
  5:  { totalSeconds: 5,  klingSeconds: 5,  klingClips: 1, strategy: 'native',  label: '5s',  available: true },
  10: { totalSeconds: 10, klingSeconds: 10, klingClips: 1, strategy: 'native',  label: '10s', available: true },
  15: { totalSeconds: 15, klingSeconds: 15, klingClips: 1, strategy: 'native',  label: '15s', available: true },
  20: { totalSeconds: 20, klingSeconds: 10, klingClips: 2, strategy: 'chained', label: '20s', available: true },
}

export const DURATION_OPTIONS = [5, 10, 15, 20] as const
export type UGCDuration = typeof DURATION_OPTIONS[number]

export interface TierConfig {
  label: string
  tagline: string
  description: string
  aRollProvider: ARollProvider
  available: boolean
}

export const TIERS: Record<UGCTier, TierConfig> = {
  standard: {
    label: 'Standard',
    tagline: 'Talking head · native audio',
    description: 'AI generates the talking head with native synced audio. Your product carries through into the first frame.',
    aRollProvider: 'kling-v3-omni',
    available: true,
  },
}

export const DEFAULT_TIER: UGCTier = 'standard'
export const DEFAULT_DURATION: UGCDuration = 10

// === Credit math — 1.8× markup on Replicate cost ===
// 1 cr = $0.025 USD.
//   BASE_FIXED: NB 2 hero frame ($0.075 cost → 5cr) + Claude + overhead ≈ 11cr at 1.8×.
//   PER_SECOND_KLING: Kling v3 omni standard-audio = $0.224/s → 8.96cr/s at cost → 16cr/s at 1.8×.
//   CHAINED_OVERHEAD_PER_CLIP: extra orchestration per chained clip.
const BASE_FIXED = 11
const PER_SECOND_KLING = 16
const CHAINED_OVERHEAD_PER_CLIP = 8

export function calculateVideoCredits(_tier: UGCTier, duration: UGCDuration): number {
  const dCfg = DURATION_CONFIGS[duration]
  if (!dCfg) return BASE_FIXED + PER_SECOND_KLING * 10

  const klingCost = PER_SECOND_KLING * dCfg.klingSeconds * dCfg.klingClips
  const chainOverhead = CHAINED_OVERHEAD_PER_CLIP * (dCfg.klingClips - 1)
  return BASE_FIXED + klingCost + chainOverhead
}

// Pre-computed for UI render perf. Single-tier now, so the outer map is trivial.
export const TIER_DURATION_CREDITS: Record<UGCTier, Record<UGCDuration, number>> = (() => {
  const row: Partial<Record<UGCDuration, number>> = {}
  for (const d of DURATION_OPTIONS) row[d] = calculateVideoCredits('standard', d)
  return { standard: row as Record<UGCDuration, number> }
})()

// Wall-clock render estimate. Kling v3 omni is ~30-90s per clip depending on duration.
export function estimateRenderSeconds(duration: UGCDuration): number {
  const dCfg = DURATION_CONFIGS[duration]
  if (!dCfg) return 120
  // Kling render time scales roughly linearly with clip length; chained clips run sequentially.
  const klingTime = dCfg.klingSeconds * 6 * dCfg.klingClips
  return Math.round(klingTime + 30) // + stitch
}

// 1 credit = $0.025 USD.
export const CREDIT_USD_VALUE = 0.025

export function creditsToUSD(credits: number): number {
  return Math.round(credits * CREDIT_USD_VALUE * 100) / 100
}

// === Standalone /generate/video pricing (unchanged — still Sora-only) ===
const BASE_STANDALONE_VIDEO = 10
const PER_SECOND_STANDALONE_VIDEO = 5

export function calculateStandaloneVideoCredits(duration: UGCDuration): number {
  // Standalone page is still on Sora 2 (different pipeline, untouched by this migration).
  const dCfg = DURATION_CONFIGS[duration]
  const seconds = dCfg?.klingSeconds ?? 10
  return BASE_STANDALONE_VIDEO + PER_SECOND_STANDALONE_VIDEO * seconds
}
